// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShippingPro.EFCore.Infra;

namespace ShippingPro.EFCore.Infra.Migrations
{
    [DbContext(typeof(ShippingProDbContext))]
    [Migration("20181024054525_added required")]
    partial class addedrequired
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShippingPro.EFCore.Domain.Model.Author", b =>
                {
                    b.Property<Guid>("AuthorID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("AuthorBirthday");

                    b.Property<string>("AuthorFirstname")
                        .IsRequired();

                    b.Property<string>("AuthorGender");

                    b.Property<bool>("AuthorIsAlive");

                    b.Property<string>("AuthorLastname");

                    b.HasKey("AuthorID");

                    b.ToTable("Author");
                });

            modelBuilder.Entity("ShippingPro.EFCore.Domain.Model.Book", b =>
                {
                    b.Property<Guid>("BookID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AuthorID");

                    b.Property<string>("BookGenre");

                    b.Property<bool>("BookIsAvailable");

                    b.Property<DateTime?>("BookPublished");

                    b.Property<string>("BookSypnosis");

                    b.Property<string>("BookTitle")
                        .IsRequired();

                    b.HasKey("BookID");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("ShippingPro.EFCore.Domain.Model.Category", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Description");

                    b.Property<byte[]>("Picture");

                    b.HasKey("CategoryID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("ShippingPro.EFCore.Domain.Model.Customer", b =>
                {
                    b.Property<Guid>("CustomerID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("ContactTitle")
                        .HasMaxLength(60);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Fax")
                        .HasMaxLength(15);

                    b.Property<string>("Phone")
                        .HasMaxLength(15);

                    b.Property<string>("PostalCode")
                        .HasMaxLength(15);

                    b.Property<string>("Region")
                        .HasMaxLength(100);

                    b.HasKey("CustomerID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("ShippingPro.EFCore.Domain.Model.Employee", b =>
                {
                    b.Property<Guid>("EmployeeID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Extension")
                        .HasMaxLength(15);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<DateTime?>("HireDate")
                        .IsRequired();

                    b.Property<string>("HomePhone")
                        .HasMaxLength(15);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("Notes")
                        .HasMaxLength(1000);

                    b.Property<byte[]>("Photo");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(15);

                    b.Property<string>("Region")
                        .HasMaxLength(100);

                    b.Property<Guid>("ReportsTo");

                    b.Property<string>("Title")
                        .HasMaxLength(60);

                    b.Property<string>("TitleOfCourtesy")
                        .HasMaxLength(60);

                    b.HasKey("EmployeeID");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("ShippingPro.EFCore.Domain.Model.Monster", b =>
                {
                    b.Property<Guid>("MonsterID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreated");

                    b.Property<bool>("IsActive");

                    b.Property<string>("MonsterName")
                        .IsRequired();

                    b.Property<decimal>("Price");

                    b.HasKey("MonsterID");

                    b.ToTable("Monster");
                });

            modelBuilder.Entity("ShippingPro.EFCore.Domain.Model.Order", b =>
                {
                    b.Property<Guid>("OrderID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CustomerID");

                    b.Property<Guid>("EmployeeID");

                    b.Property<decimal>("Freight");

                    b.Property<DateTime>("OrderDate");

                    b.Property<DateTime>("RequiredDate");

                    b.Property<string>("ShipAddress")
                        .HasMaxLength(100);

                    b.Property<string>("ShipCity")
                        .HasMaxLength(100);

                    b.Property<string>("ShipCountry")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ShipName")
                        .HasMaxLength(100);

                    b.Property<string>("ShipPostalCode")
                        .HasMaxLength(15);

                    b.Property<string>("ShipRegion")
                        .HasMaxLength(100);

                    b.Property<DateTime>("ShippedDate");

                    b.Property<Guid>("ShipperID");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("ShipperID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("ShippingPro.EFCore.Domain.Model.OrderDetail", b =>
                {
                    b.Property<Guid>("OrderDetailID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Discount");

                    b.Property<Guid>("OrderID");

                    b.Property<int>("OrderLineID");

                    b.Property<Guid>("ProductID");

                    b.Property<decimal>("Quantity");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("OrderDetailID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("ShippingPro.EFCore.Domain.Model.Person", b =>
                {
                    b.Property<Guid>("PersonID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BaranggaySubdivision");

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("Country")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("Gender")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<int>("Latitude");

                    b.Property<int>("Longtitude");

                    b.Property<string>("MiddleName");

                    b.Property<string>("Nationality")
                        .IsRequired();

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.Property<byte[]>("Photo");

                    b.Property<int>("PostalCode");

                    b.Property<string>("Region")
                        .IsRequired();

                    b.Property<string>("RelationshipStatus")
                        .IsRequired();

                    b.Property<string>("Religion")
                        .IsRequired();

                    b.Property<string>("StreetHouseBuilding")
                        .IsRequired();

                    b.HasKey("PersonID");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("ShippingPro.EFCore.Domain.Model.Product", b =>
                {
                    b.Property<Guid>("ProductID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CategoryID");

                    b.Property<bool>("Discontinued");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<decimal>("ReorderLevel");

                    b.Property<Guid>("SupplierID");

                    b.Property<decimal>("UnitPrice");

                    b.Property<decimal>("UnitsInStock");

                    b.Property<decimal>("UnitsOnOrder");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("SupplierID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("ShippingPro.EFCore.Domain.Model.Shipper", b =>
                {
                    b.Property<Guid>("ShipperID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.HasKey("ShipperID");

                    b.ToTable("Shipper");
                });

            modelBuilder.Entity("ShippingPro.EFCore.Domain.Model.Supplier", b =>
                {
                    b.Property<Guid>("SupplierID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("ContactTitle")
                        .HasMaxLength(60);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Fax")
                        .HasMaxLength(15);

                    b.Property<string>("HomePage")
                        .HasMaxLength(100);

                    b.Property<string>("Phone")
                        .HasMaxLength(15);

                    b.Property<string>("PostalCode")
                        .HasMaxLength(15);

                    b.Property<string>("Region")
                        .HasMaxLength(100);

                    b.HasKey("SupplierID");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("ShippingPro.EFCore.Domain.Model.Order", b =>
                {
                    b.HasOne("ShippingPro.EFCore.Domain.Model.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShippingPro.EFCore.Domain.Model.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShippingPro.EFCore.Domain.Model.Shipper", "ShipVia")
                        .WithMany()
                        .HasForeignKey("ShipperID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShippingPro.EFCore.Domain.Model.OrderDetail", b =>
                {
                    b.HasOne("ShippingPro.EFCore.Domain.Model.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShippingPro.EFCore.Domain.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShippingPro.EFCore.Domain.Model.Product", b =>
                {
                    b.HasOne("ShippingPro.EFCore.Domain.Model.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShippingPro.EFCore.Domain.Model.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
